// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_CE0eDyH5vJ5rZup_5XNFMgArC6xq-g',
    appId: '1:427612490525:android:69942fbef774c62db4aff4',
    messagingSenderId: '427612490525',
    projectId: 'mercado-cercano-28190',
    storageBucket: 'mercado-cercano-28190.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE95PTro1E0Zrs7aY8-PVt3Tyqmg0rK5g',
    appId: '1:427612490525:ios:9b551cb679f71546b4aff4',
    messagingSenderId: '427612490525',
    projectId: 'mercado-cercano-28190',
    storageBucket: 'mercado-cercano-28190.firebasestorage.app',
    androidClientId: '427612490525-ug4jptp5pubbj4v1t14n1rsssbjq6708.apps.googleusercontent.com',
    iosClientId: '427612490525-rbk8u8mrua12ripepc8qmj3e85d4b5vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mercadoCercano',
  );
}
